name: Deploy to IPFS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.1.0
        with:
          pinataApiKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecretApiKey: ${{ secrets.PINATA_SECRET_API_KEY }}
          path: './'

